### PR TITLE
Feature importances for FForest.

### PR DESCRIPTION
**Pull request by jendelel**

### CODE REVIEW

**Comment by rdk** [comment]
Dik za patch, ale Travis mi rika ze je tam chybka https://travis-ci.org/rdk/p2rank/builds/226947283 .. duplicitni radek?

**Comment by rdk** [comment]
check travis again... "unable to resolve class FasterForest"... probably missing import

**Comment by jendelel** [comment]
Yep, I noticed. That's what happens, when you do the changes directly from GitHub. Next time, I will do it locally and push the changes. 
Hopefully, it will pass now.
Thanks!

**Comment by rdk** [comment]
i see the problem now. don't merge it to the master but to develop. it's way ahead

**Comment by jendelel** [comment]
Yes, I noticed it now as well.

**Pull request closed without merging**
